#! usr/bin/env bash

pgrep -x sxhkd > /dev/null || sxhkd &
# pkill -USR1 -x sxhkd &
xsetroot -cursor_name left_ptr &
xset r rate 200 25 &
picom &
feh --bg-fill ~/photos/wallpaper/GJXis6KbEAA2DVF.png &
ibus-daemon -drxR &
# nm-applet &
# setxkbmap -option caps:swapescape &
pgrep -x battery-alert >/dev/null || ~/bin/battery-alert &
pidof redshift || redshift -l "12:125" -t "6500:3200" &
pidof syncthing || syncthing -no-browser &
trash-empty -f 30 &
# wmname LG3D & # This is for IntellJ and IntellJ-based (Android Studio)
copyq &

# bspc wm -O eDP-1-0 HDMI-A-1-0
# bspc monitor eDP-1-0 -d 1 2 3 4 5 6 7
# bspc monitor HDMI-A-1-0 -d 8
bspc monitor -d I II III IV V VI VII VII IX X

bspc config border_width 2
bspc config window_gap 15

bspc config focused_border_color \#bf0086

bspc config split_ratio 0.55
bspc config borderless_monocle true
bspc config gapless_monocle true

# bspc config focus_follows_pointer true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action2 resize_corner

bspc rule -a firefox desktop=^2
bspc rule -a discord desktop=^3
bspc config external_rules_command "$HOME/bin/spotify-rule"